pipeline {
    agent any
    tools{
        maven "M2_HOME"
    }
    stages {
        stage('GIT') {
            steps {
                git branch: "main",
                url: "https://github.com/amanibensassi/jenkinsFile.git"
            }
        }
        stage('clean') {
            steps {
                sh 'mvn clean compile';
            }
        }
    }
}
